# Generated by Django 6.0.4 on 2026-05-17 07:48

from django.db import migrations


def encrypt_existing_keys(apps, schema_editor):
    UserAPIKey = apps.get_model("authentication", "UserAPIKey")
    # Reading via our custom EncryptedCharField will gracefully fall back to
    # returning plaintext if the value cannot be decrypted.
    # Saving it will run it through get_prep_value which encrypts it.
    for key in UserAPIKey.objects.all():
        # Only re-save to trigger encryption
        key.save(update_fields=["api_key"])


def reverse_encrypt_existing_keys(apps, schema_editor):
    pass  # We don't want to decrypt them back to plaintext automatically


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_userapikey"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_keys, reverse_encrypt_existing_keys),
    ]
