"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import corsheaders.defaults
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

FERNET_KEYS_ENV = os.getenv("FERNET_KEY")
if not FERNET_KEYS_ENV:
    raise ValueError(
        "FERNET_KEY environment variable is not set. "
        "Generate one with: python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'"
    )
FERNET_KEYS = [FERNET_KEYS_ENV]

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://anuj6316-pm-bot-backend.hf.space",
]


# Application definition

INSTALLED_APPS = [
    "daphne",  # must be first so it handles ASGI
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # custom apps
    "authentication",
    "agent",
    "chat",
    "integrations",
    # 3rd parties
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_celery_results",
    "channels",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DJANGO_POSTGRES_DB", os.getenv("POSTGRES_DB", "postgres")),
        "USER": os.getenv(
            "DJANGO_POSTGRES_USER", os.getenv("POSTGRES_USER", "postgres")
        ),
        "PASSWORD": os.getenv(
            "DJANGO_POSTGRES_PASSWORD",
            os.getenv("POSTGRES_PASSWORD", ""),
        ),
        "HOST": os.getenv("POSTGRES_HOST", ""),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.getenv("POSTGRES_SSLMODE", "require"),
        },
    }
}

# Support for DATABASE_URL if provided (e.g., Supabase connection string)
import dj_database_url

db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=True)
if db_from_env:
    DATABASES["default"].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

## Celery
# The broker is Redis — where Django pushes tasks and Celery pulls from
# Celery and Redis configuration
# Use REDIS_HOST env var if set (for supervisord/HF Spaces), otherwise default to 'redis' for docker-compose
_REDIS_HOST = os.getenv("REDIS_HOST", "localhost" if os.path.exists("/.dockerenv") is False else "redis")
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", f"redis://{_REDIS_HOST}:6379/0")

# The result backend — where Celery stores task status and return values
# 'django-db' means results are stored in PostgreSQL via django_celery_results
CELERY_RESULT_BACKEND = "django-db"

# Serialize task arguments and results as JSON (safer than pickle)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Store task results for 7 days before they expire
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7

# Timezone must match Django
CELERY_TIMEZONE = TIME_ZONE

# Automatically find tasks in any tasks.py file inside INSTALLED_APPS
CELERY_AUTODISCOVER_TASKS = True

# Beat Schedule
CELERY_BEAT_SCHEDULE = {
    "poll-plane-every-5-minutes": {
        "task": "agent.tasks.poll_plane_issues",
        "schedule": 300.0,  # 5 minutes
    },
}

AUTH_USER_MODEL = "authentication.User"

# Add this at the bottom of settings.py
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========================
# REST Framework & JWT
# ========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ========================
# CORS Origins
# ========================
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(
    ","
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    *corsheaders.defaults.default_headers,
]

# ========================
# Django Channels (WebSocket)
# ========================
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(_REDIS_HOST, 6379)],
        },
    }
}

# ========================
# Chatbot Configuration
# ========================
# Max messages a user can send per minute (rate limiting)
CHATBOT_RATE_LIMIT = int(os.getenv("CHATBOT_RATE_LIMIT", "20"))
# Max characters per user message
CHATBOT_MAX_MESSAGE_LENGTH = int(os.getenv("CHATBOT_MAX_MESSAGE_LENGTH", "4096"))
# Max seconds to wait for agent response before timeout
CHATBOT_AGENT_TIMEOUT = int(os.getenv("CHATBOT_AGENT_TIMEOUT", "120"))
# Max tool call iterations in a single agent turn
CHATBOT_AGENT_MAX_ITERATIONS = int(os.getenv("CHATBOT_AGENT_MAX_ITERATIONS", "10"))

# ========================
# DRF Spectacular (Swagger/OpenAPI)
# ========================
SPECTACULAR_SETTINGS = {
    "TITLE": "PM Bot API",
    "DESCRIPTION": "Project Management Bot API with Plane integration and AI chatbot",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    "SECURITY": [
        {
            "bearerAuth": [],
        },
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

# ========================
# Logging Configuration
# ========================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "detailed": {
            "format": "{levelname} {asctime} {module} {funcName}:{lineno} → {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "detailed",
        },
    },
    "loggers": {
        "authentication": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "integrations": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

## Printing the ENV from prod
target_keys = [
    "PLANE_BASE_URL",
    "PLANE_WORKSPACE_SLUG",
    "PLANE_API_KEY",
    "DATABASE_URL",
    "REDIS_URL",
    "CELERY_BROKER_URL",
    "CELERY_BROKER_URL",
    "DJANGO_SECRET_KEY",
    "DJANGO_SUPERUSER_EMAIL",
    "DJANGO_SUPERUSER_USERNAME",
    "DJANGO_SUPERUSER_PASSWORD",
]
import os
print("--- BEGIN ENV EXPORT ---\n")
for key in target_keys:
    val = os.getenv(key)
    if val:
        print(f"{key}={val}")
print("--- END ENV EXPORT ---\n")
