# Generated by Django 6.0.4 on 2026-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentissuesession',
            name='draft_response',
            field=models.TextField(blank=True, help_text="Stores the AI's draft response for review", null=True),
        ),
        migrations.AddField(
            model_name='agentissuesession',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentissuesession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
    ]
