# Generated by Django 6.0.4 on 2026-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentissuesession',
            name='issue_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentissuesession',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
