# Generated by Django 6.0.4 on 2026-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentissuesession_issue_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentissuesession',
            name='issue_title',
        ),
        migrations.RemoveField(
            model_name='agentissuesession',
            name='project_name',
        ),
        migrations.AddField(
            model_name='agentissuesession',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
